language: php
php:
    - 5.5
    - 5.4
    - hhvm
script:
    #- phpunit --bootstrap test/config.php test
    - phpunit --bootstrap test/config.php --coverage-clover coverage.clover test

before_script:
    - composer install
    - wget https://scrutinizer-ci.com/ocular.phar

after_script:
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
